Домашнее задание к третьей паре
tend3r/garbage pull request #4
Opened 2020-04-03 14:16 UTC by tend3r

2020-04-05 11:44 UTC, mashinapetro requested changes

2020-04-05 11:44 UTC, mashinapetro commented on LoginForm/main.qml
> +            font.underline: (status == 0) ? true : false
Выражение (status == 0) уже является логическим, т.е. возвращает значение true или false. Тернарный оператор тут не нужен.

2020-04-05 11:44 UTC, mashinapetro commented on LoginForm/main.qml
> +            font.underline: (status == 1) ? true : false
Выражение (status == 1) уже является логическим, т.е. возвращает значение true или false. Тернарный оператор тут не нужен.

2020-04-05 11:44 UTC, mashinapetro commented on LoginForm/RegistrationForm.qml
> +
Лишняя пустая строка.

2020-04-05 11:44 UTC, mashinapetro commented on LoginForm/ClickableText.qml
> +                   id: mouseSignUp
Отступы уехали.

2020-04-05 11:44 UTC, mashinapetro commented on LoginForm/ClickableText.qml
> +                       login.text = ""
Вот это зачем?
Компонент ClickableText должен только уведомлять о том, что он нажат. И все. Все эти изменения свойств не дадут возможности использовать такой компонент где-либо еще.

2020-04-06 08:34 UTC, tend3r commented on LoginForm/main.qml
> +            font.underline: (status == 0) ? true : false
Исправил

2020-04-06 08:34 UTC, tend3r commented on LoginForm/main.qml
> +            font.underline: (status == 1) ? true : false
Исправил

2020-04-06 08:35 UTC, tend3r commented on LoginForm/main.qml
> +            font.underline: (status == 1) ? true : false
> Выражение (status == 1) уже является логическим, т.е. возвращает значение true или false. Тернарный оператор тут не нужен.

Исправил

2020-04-06 08:35 UTC, tend3r commented on LoginForm/main.qml
> +            font.underline: (status == 0) ? true : false
> Выражение (status == 0) уже является логическим, т.е. возвращает значение true или false. Тернарный оператор тут не нужен.

Исправил

2020-04-06 08:38 UTC, tend3r commented on LoginForm/RegistrationForm.qml
> +
> Лишняя пустая строка.

Исправил

2020-04-06 08:44 UTC, tend3r commented on LoginForm/ClickableText.qml
> +                   id: mouseSignUp
> Отступы уехали.

Исправил

2020-04-06 08:47 UTC, tend3r commented on LoginForm/ClickableText.qml
> +                       login.text = ""
> Вот это зачем?
> Компонент ClickableText должен только уведомлять о том, что он нажат. И все. Все эти изменения свойств не дадут возможности использовать такой компонент где-либо еще.

Так ведь нам нужно очищать поля в формах при переключении с Sign In на Sign Up, разве нет? Или нужно эти свойства вынести в формы?

2020-04-06 13:23 UTC, mashinapetro commented on LoginForm/main.qml
> +            font.underline: (status == 0) ? true : false
Ок.

2020-04-06 13:24 UTC, mashinapetro commented on LoginForm/main.qml
> +            font.underline: (status == 1) ? true : false
Ок.

2020-04-06 13:56 UTC, mashinapetro commented on LoginForm/RegistrationForm.qml
> +
Ок

2020-04-06 13:57 UTC, mashinapetro commented on LoginForm/ClickableText.qml
> +                       login.text = ""
Если это и надо делать, то вне этого компонента. Уже в обработчике нажатия надо вызывать какие-то функции.

2020-04-06 14:27 UTC, tend3r commented on LoginForm/ClickableText.qml
> +                       login.text = ""
> Если это и надо делать, то вне этого компонента. Уже в обработчике нажатия надо вызывать какие-то функции.

Исправил

2020-04-06 16:11 UTC, mashinapetro approved these changes

2020-04-06 16:15 UTC, merged